Спринт 9
DIXX159/java-filmorate pull request #1
Opened 2022-11-15 17:33 UTC by DIXX159

2022-11-16 15:52 UTC, DIXX159 commented
Созданы контроллеры, добавлены валидация и логирование.

2022-11-16 18:55 UTC, EvgenyKoptubenko commented on src/test/java/ru/yandex/practicum/filmorate/FilmControllerTest.java
> +    void postFilmTest() throws ValidationException {
Два теста отличаются друг от друга только одним параметром. Если есть желание, попробуй написать параметризованный тест https://www.baeldung.com/parameterized-tests-junit-5

2022-11-16 19:04 UTC, EvgenyKoptubenko commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        int id = idGenerator++;
Нужно добавить логирование в основные контроллеры. Логирование нужно для того, чтобы можно было отлаживать на проде и для настройки мониторинга

2022-11-16 19:06 UTC, EvgenyKoptubenko commented on src/main/java/ru/yandex/practicum/filmorate/exceptions/ValidationException.java
> +package ru.yandex.practicum.filmorate.exceptions;
Пакеты лучше именовать в единственном числе. У тебя где-то в единственном, где-то во множественном. 
(Это необязательный комментарий)

2022-11-16 19:14 UTC, EvgenyKoptubenko commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        throw new ValidationException("список фильмов пуст");
Почему возвращается эксепшн, когда на самом деле все работает верно. Т.е. если список пуст, то почему не вернуть клиенту просто пустой список?
Сейчас он получает ошибку
{
	"timestamp": "2022-11-16T19:13:37.504+00:00",
	"status": 500,
	"error": "Internal Server Error",
	"path": "/films"
}

2022-11-16 19:16 UTC, EvgenyKoptubenko commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private String releaseDate;
Почему дата это строка? Ведь можно сразу использовать тип данных для даты

2022-11-16 19:18 UTC, EvgenyKoptubenko commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public static Film create(@Valid @RequestBody @NotNull Film film) throws ValidationException {
Согласно спецификации можно передавать дату в формате 2020-05-12T23:50:21.817Z
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date

Если передать такое тело:
{
	"name":"FilmName",
	"description":"descriptionItem",
	"duration": 22,
	"releaseDate": "2012-04-23T18:25:43.511Z",
	"mpa":{
	  "id":"1",
		"name":"2223"
}
}
То падает
java.time.format.DateTimeParseException: Text '2012-04-23T18:25:43.511Z' could not be parsed, unparsed text found at index 10
	at java.base/java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:2055) ~[na:na]
	at java.base/java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1954) ~[na:na]
	at java.base/java.time.LocalDate.parse(LocalDate.java:430) ~[na:na]
	at ru.yandex.practicum.filmorate.controller.FilmController.getFilm(FilmController.java:60) ~[classes/:na]
	at ru.yandex.practicum.filmorate.controller.FilmController.create(FilmController.java:36)

2022-11-16 19:21 UTC, EvgenyKoptubenko commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        int id = idGenerator++;
Не хватает валидации. Если не передать дату рождения, то происходит NullPointerException
{
	"name":"nameItem",
	"email":"email3@email.com",
  "login":"login"
}

java.lang.NullPointerException: text
	at java.base/java.util.Objects.requireNonNull(Objects.java:233) ~[na:na]
	at java.base/java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1951) ~[na:na]
	at java.base/java.time.LocalDate.parse(LocalDate.java:430) ~[na:na]
	at ru.yandex.practicum.filmorate.controller.UserController.getUser(UserController.java:60) ~[classes/:na]
	at ru.yandex.practicum.filmorate.controller.UserController.create(UserController.java:38)

2022-11-16 19:22 UTC, EvgenyKoptubenko commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    static DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-d");
Для чего форматировать так дату? Используй стандартный класс - он сам распарсит вводимые данные. Чем плохо хранить дату со временем

2022-11-16 19:24 UTC, EvgenyKoptubenko requested changes
Попробуй работать со стандартной датой, которая содержит время. Есть еще несколько замечаний. В целом работа хорошая.

2022-11-17 15:23 UTC, DIXX159 commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        int id = idGenerator++;
По ТЗ нужна дата релиза фильма. Время там лишнее...

2022-11-17 15:24 UTC, DIXX159 commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    static DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-d");
По ТЗ нужна дата релиза фильма. Время там лишнее...

2022-11-17 15:24 UTC, DIXX159 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public static Film create(@Valid @RequestBody @NotNull Film film) throws ValidationException {
По ТЗ нужна дата релиза фильма. Время там лишнее...

2022-11-17 18:13 UTC, EvgenyKoptubenko approved these changes
Если считаешь замечания поправленными, то других у меня нет. Работа сделана хорошо.

2022-11-22 13:22 UTC, merged