Add friends likes
DIXX159/java-filmorate pull request #2
Opened 2022-11-27 15:28 UTC by DIXX159

2022-11-27 16:27 UTC, EvgenyKoptubenko commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public User create(@Valid @RequestBody @NotNull User user) {
Попробуй сделать так, чтобы пользователю приходило просто сообщение об ошибке без подробностей что сломалось в коде
{
	"error": "Ошибка валидации.",
	"errorMessage": "Validation failed for argument [0] in public ru.yandex.practicum.filmorate.model.User ru.yandex.practicum.filmorate.controller.UserController.create(ru.yandex.practicum.filmorate.model.User): [Field error in object 'user' on field 'email': rejected value [email3email.com]; codes [Email.user.email,Email.email,Email.java.lang.String,Email]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [user.email,email]; arguments []; default message [email],[Ljavax.validation.constraints.Pattern$Flag;@7972f8fe,.*]; default message [Неправильный Email]] "
}

2022-11-27 16:30 UTC, EvgenyKoptubenko commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    private final Logger logger = LoggerFactory.getLogger(UserController.class);
Логгер дожен быть свой для каждого класса. Сейчас для сервиса используется логгер контроллера. Лучше использовать Lombok для добавления логера

2022-11-27 16:31 UTC, EvgenyKoptubenko commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (films.get(filmId) != null & InMemoryUserStorage.getUsers().get(userId) != null) {
Лучше использовать &&, что не вычислять вторую часть, если первая не проходит

2022-11-27 16:33 UTC, EvgenyKoptubenko commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public FilmService() {
Тут ничего не автовайрится. Этот конструктор не нужен

2022-11-27 16:33 UTC, EvgenyKoptubenko commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    public UserService() {
Этот конструктор не нужен.

2022-11-27 16:46 UTC, EvgenyKoptubenko commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        } else throw new NotFoundException("Пользователь не найден");
По всему коду очень много разбросано дублирующихся констант. Предлагаю их вынести куда-нибудь в отдельный класс, если есть желание.

2022-11-27 16:47 UTC, EvgenyKoptubenko commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        return filmService.findFilmById(filmId);
Лучше добавить во все контроллеры логирование, чтобы можно было проще отлаживать приложение в продакшене.
Если есть желание.

2022-11-27 16:48 UTC, EvgenyKoptubenko commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +        return idGenerator = 1;
Для чего тут возвращаемое значение? Ведь генератор статический. Возвращаемым значением никто не пользуется

2022-11-27 16:50 UTC, EvgenyKoptubenko requested changes
Работа сделана очень хорошо. Все работает по ТЗ. Есть только замечания из разряда "можно лучше". Если есть желание, поправь, пожалуйста. Если нет - присылай обратно

2022-11-28 15:07 UTC, DIXX159 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (films.get(filmId) != null & InMemoryUserStorage.getUsers().get(userId) != null) {
Заменил

2022-11-28 15:09 UTC, DIXX159 commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    public UserService() {
Убрал

2022-11-28 15:11 UTC, DIXX159 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +        return idGenerator = 1;
Исправил

2022-11-29 13:02 UTC, DIXX159 commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        } else throw new NotFoundException("Пользователь не найден");
сделал

2022-11-29 13:03 UTC, DIXX159 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        return filmService.findFilmById(filmId);
оставил без изменений

2022-11-29 14:36 UTC, DIXX159 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    private final Logger logger = LoggerFactory.getLogger(UserController.class);
исправил

2022-11-29 15:58 UTC, DIXX159 commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public User create(@Valid @RequestBody @NotNull User user) {
исправил

2022-11-29 20:46 UTC, EvgenyKoptubenko approved these changes
Работа сделана отлично! Спасибо

2022-11-30 13:38 UTC, merged