ТЗ11 на проверку
DIXX159/java-filmorate pull request #3
Opened 2023-01-06 05:09 UTC by DIXX159

2023-01-06 14:27 UTC, EvgenyKoptubenko commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        return userDbStorage.updateUser(user);
Если создавать пользователя  с неверным email,  то приходит ошибка
{
	"Ошибка": "Неправильный Email"
}
Если делать йапдейт с неверной почтой, то приходит 500
{
	"error": "Произошла непредвиденная ошибка."
}

2023-01-06 14:31 UTC, EvgenyKoptubenko commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Film createFilm(@Valid @RequestBody Film film) {
Если добавлять один и тот же фильм, то в первый раз фильм создается, во второй раз приходит 500
{
	"error": "Произошла непредвиденная ошибка."
}
Но при этом фильм добавляется.

[
	{
		"id": 1,
		"name": "Film2Name",
		"description": "2descriptionItem",
		"releaseDate": "2012-04-23",
		"duration": 222,
		"rate": 0,
		"mpa": {
			"id": 1,
			"name": "G"
		},
		"genres": [
			{
				"id": 1,
				"name": "Комедия"
			}
		]
	},
	{
		"id": 2,
		"name": "Film2Name",
		"description": "2descriptionItem",
		"releaseDate": "2012-04-23",
		"duration": 222,
		"rate": 0,
		"mpa": {
			"id": 1,
			"name": "G"
		},
		"genres": []
	},
	{
		"id": 3,
		"name": "Film2Name",
		"description": "2descriptionItem",
		"releaseDate": "2012-04-23",
		"duration": 222,
		"rate": 0,
		"mpa": {
			"id": 1,
			"name": "G"
		},
		"genres": []
	}
]

2023-01-06 14:41 UTC, EvgenyKoptubenko requested changes
Работа сделана хорошо. Всего несколько замечаний.

2023-01-07 07:42 UTC, DIXX159 commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        return userDbStorage.updateUser(user);
Исправил.

2023-01-07 08:09 UTC, DIXX159 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Film createFilm(@Valid @RequestBody Film film) {
Исправил.

2023-01-07 08:22 UTC, DIXX159 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        return filmDbStorage.getPopularFilms(count);
Добавил.

2023-01-07 17:34 UTC, EvgenyKoptubenko approved these changes
Работа сделана отлично. Спасибо

2023-01-08 04:55 UTC, merged